* integrate latest ubuntu changes   * remaining changes:     - use quilt as patch system (instead of dpatch)     - fixed lint warnings concerning apache2 configs     - include patched version of mysql_slave

diff --git a/debian/check-mk-config-nagios3.postinst b/debian/check-mk-config-nagios3.postinst
--- a/debian/check-mk-config-nagios3.postinst
+++ b/debian/check-mk-config-nagios3.postinst
@@ -21,6 +21,16 @@ dpkg-maintscript-helper mv_conffile \
     /etc/nagios3/conf.d/check_mk/check_mk_templates.cfg \
     1.1.10-2 -- "$@"
 
+# older releases (1.1.12p7-1 at least) delivered the multisite conffile to
+# /etc/apache2/conf.d. If it exists we need to move it to conf-available
+# once it's moved then the code below will setup the conf.d symlink.
+# This code wasn't in place until 1.2.6p4-2, so we need to check everything
+# before that.
+dpkg-maintscript-helper mv_conffile \
+    /etc/apache2/conf.d/check_mk_multisite.cfg \
+    /etc/apache2/conf-available/check_mk_multisite.cfg \
+    1.2.6p4-2 -- "$@"
+
 if [ -e '/etc/nagios3/conf.d/check_mk_objects.cfg' ];
 then
     echo 'Migrate /etc/nagios3/conf.d/check_mk_objects.cfg to /etc/nagios3/conf.d/objects/check_mk/check_mk_objects.cfg'
@@ -48,7 +58,18 @@ case "$1" in
                         . /usr/share/apache2/apache2-maintscript-helper
                         apache2_invoke enconf $CONF || exit $?
                 elif [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
-                        [ -d /etc/apache2/conf.d/ ] && [ ! -L /etc/apache2/conf.d/$CONF.conf ] && ln -s ../conf-available/$CONF.conf /etc/apache2/conf.d/$CONF.conf
+                        if [ -d /etc/apache2/conf.d/ ]; then
+                                if [ -L /etc/apache2/conf.d/$CONF.conf ]; then
+                                        # it's a symlink, all is well
+                                        true
+                                elif [ -e /etc/apache2/conf.d/$CONF.conf ]; then
+                                        # it's not a symlink, but exists, error
+                                        echo "ERROR: /etc/apache2/conf.d/$CONF.conf is not a symlink, please investigate" 1>&2
+                                else
+                                        # we need to create the symlink
+                                        ln -s ../conf-available/$CONF.conf /etc/apache2/conf.d/$CONF.conf
+                                fi
+                        fi
                 fi
     ;;
   abort-upgrade|abort-remove|abort-deconfigure)
